### PR TITLE
Fix Django 5.2 compatibility

### LINKED ISSUE #785: Django 5.2 compatibility
### `display_for_field` changes
In [a9c79b4](https://github.com/django/django/commit/a9c79b462923ce366101db1b5a3fff3d1dad870c), a new keyword argument was added to `display_for_field`.

This needs to be updated in the monkey-patching done in `djmoney/admin.py`, https://github.com/django-money/django-money/blob/835c1ab867d11137b964b94936692bea67a038ec/djmoney/admin.py#L14-L17

### Removal of `django.core.serializers.python._get_model`
In [ee5147c](https://github.com/django/django/commit/ee5147cfd7de2add74a285537a8968ec074e70cd), the deserializer was refactored into a class.

The [docs on Custom serialization formats](https://docs.djangoproject.com/en/5.2/topics/serialization/#custom-serialization-formats) suggests using a class

### PR DESCRIPTION
**Pull request by gvangool**
Fix the 2 compatibility issues discovered while testing the Django 5.2 beta.

- a new keyword argument was added to `display_for_field`.
- removal of `django.core.serializers.python._get_model`

Fixes #785

Thanks @browniebroke for the assist!

### CODE REVIEW

**Review by browniebroke — COMMENTED** [review]
Nice fix!

File: tox.ini [hunk 1]
```diff
@@ -1,7 +1,7 @@
 [tox]
 envlist =
     django_main-py{312,311,310}
```
[the remark this answers is not in the document]
Comment (gvangool) [reply tox.ini]: Thank for that reminder 👍 
I've also included the Python 3.13 compatibility

[the remark this answers is not in the document]
Comment (browniebroke) [reply tox.ini]: Even better 😄 🎉

[the remark this answers is not in the document]
Comment (browniebroke) [reply tox.ini]: Although you may want to update the classifiers accordingly:

https://github.com/django-money/django-money/blob/835c1ab867d11137b964b94936692bea67a038ec/setup.py#L63-L68

**Comment by browniebroke** [comment]
Gave a try to handle the 2nd incompatibility here: https://github.com/gvangool/django-money/pull/1

File: djmoney/admin.py [hunk 2]
```diff
@@ -11,10 +12,12 @@
 def setup_admin_integration():
     original_display_for_field = admin_utils.display_for_field
 
-    def display_for_field(value, field, empty):
+    def display_for_field(value, field, empty, avoid_link=False):
```
Comment (bmispelon) [inline djmoney/admin.py:15]: To avoid having to test against a specific Django version you could also do:
```
def display_for_field(value, field, *args, **kwargs):
    if isinstance(field, MoneyField):
        return str(value)
    return original_display_for_field(value, field, *args, **kwargs)
```

This would also make the code more resistant to other changes to the signature in the future.

**Comment by benjaoming** [comment]
Hey! Sorry for the late response! Would be super-happy to merge this @gvangool - great work!

Running the tests now, and otherwise it looks good. Would you be able to address the comment from @bmispelon - seems like a nice quick addition? :pray:

**Comment by gvangool** [comment]
> ```
>         File "/tmp/pip-req-build-q1v1u_pi/django/utils/version.py", line 99, in get_git_changeset
>           tz = datetime.UTC
>       AttributeError: module 'datetime' has no attribute 'UTC'
> ```
> 
> Hmm looks like the `main` branch of Django does't work with Python 3.10 anymore?

Correct, it's only Python 3.12+

I updated `tox.ini`, but not `.github/workflows/main.yml`

**Comment by seibti** [comment]
Could someone please approve this PR, django 5.2 is out now and its blocking my dependencies updats

**Comment by browniebroke** [comment]
> Could someone please approve this PR, django 5.2 is out now and its blocking my dependencies updates

If you're really in a rush, you can do one of the following:

- `pip install https://github.com/gvangool/django-money/archive/issues/785.zip`
- `poetry add https://github.com/gvangool/django-money/archive/issues/785.zip`
- `uv add https://github.com/gvangool/django-money/archive/issues/785.zip`

**Review by benjaoming — APPROVED** [review]
Thanks for this!! :pray: :rocket:

**Comment by benjaoming** [comment]
Hey! Thanks once again - this should be released now :crossed_fingers:
