### ISSUE TITLE
error when trying to print a MoneyField in django 1.8

### ISSUE THREAD

**Issue by YAmikep** [django-money/django-money#124]
Printing the field does not work with django 1.8.
I started a project from scratch and added the model from the documentation, I got this error:

```
>>> p =  BankAccount.objects.first()
>>> p.balance
10 USD
>>> print(p.balance)
None
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/projects/projects/django-money/djmoney/models/fields.py", line 134, in __str__
    locale = self.__get_current_locale()
  File "/projects/projects/django-money/djmoney/models/fields.py", line 104, in __get_current_locale
    locale = translation.to_locale(translation.get_language())
  File "/home/vagrant/dev/lib/python3.4/site-packages/django/utils/translation/__init__.py", line 185, in to_locale
    return _trans.to_locale(language)
  File "/home/vagrant/dev/lib/python3.4/site-packages/django/utils/translation/trans_real.py", line 75, in to_locale
    p = language.find('-')
AttributeError: 'NoneType' object has no attribute 'find'
```
The reason is because in [here](https://github.com/django-money/django-money/blob/master/djmoney/models/fields.py#L103), `translation.get_language()` is used directly in `translation.to_locale` while `translation.get_language()` can return `None` in django 1.8 which throws an error.

https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.translation.get_language

**Comment by benjaoming** [comment]
Thanks for the PR and the description! Closing this, let me know if there's any other occurrences that need fixing and if you can work on this!
