### PR TITLE
Revert #726 - fixes #731

### LINKED ISSUE #731: 'MoneyField' object has no attribute '_currency_field' when running migration
Hi there,

I have a migration to add the following field:

```
from djmoney.models.fields import MoneyField

class Invoice(Model):
    my_amount = MoneyField(max_digits=14, decimal_places=2, default="0 USD")

```

I added some code to update this field in a view and that all appears to be working fine. 

Now I want to add a data migration like below:
```

from djmoney.money import Money

from django.db import migrations

def migrate_invoices(app, _):
    Invoice = app.get_model("users", "Invoice")
    for invoice in Invoice.objects.all():
        invoice.my_amount = Money(10, 'AUD')
        invoice.save()
 

class Migration(migrations.Migration):

    operations = [
        migrations.RunPython(migrate_invoices, migrations.RunPython.noop)
    ]

```

However this is producing the following error:

```
  File "/app/myapp/users/migrations/0159_auto_20230929_0113.py", line 9, in migrate_invoices
    for invoice in Invoice.objects.all():
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 69, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 515, in from_db
    new = cls(*values)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 437, in __init__
    _setattr(self, field.attname, val)
  File "/usr/local/lib/python3.9/site-packages/djmoney/models/fields.py", line 111, in __set__
    and self.field._currency_field.null
AttributeError: 'MoneyField' object has no attribute '_currency_field'

```

Not sure if I'm missing something? 

Project uses:
* Django 3.2.19
* Python 3.9
* Django-money 3.3

### PR DESCRIPTION
**Pull request by benjaoming**
Fairly convinced from the feedback that this is the right thing to do.

If someone wants to gift django-money a test suite that can test its behavior in migrations, that would be lovely. @Stranger6667 shared some good ideas in https://github.com/django-money/django-money/issues/731#issuecomment-1996835661.

### CODE REVIEW

**Review by jpells — APPROVED** [review]
Issue #731 is affecting my app

After reading through Issue #725 I also believe this PR should be reverted and the issue can be re-opened for another attempt

**Review by Stranger6667 — APPROVED** [review]
:+1:
