### ISSUE TITLE
Regression in 3.5 - AttributeError: type object 'Meta' has no attribute 'model'

### ISSUE THREAD

**Issue by phillipuniverse** [django-money/django-money#757]
Looks to be caused by https://github.com/django-money/django-money/pull/722.

Django - 4.2.11
DRF - 3.14.0

```
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-backend-core-cpwchxt0-py3.11/lib/python3.11/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-backend-core-cpwchxt0-py3.11/lib/python3.11/site-packages/rest_framework/serializers.py", line 481, in to_internal_value
    primitive_value = field.get_value(data)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/phillip/Library/Caches/pypoetry/virtualenvs/shipwell-backend-core-cpwchxt0-py3.11/lib/python3.11/site-packages/djmoney/contrib/django_rest_framework/fields.py", line 70, in get_value
    model_meta = self.parent.Meta.model._meta
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Meta' has no attribute 'model'
```

I think this is an edge case when using a `MoneyField` with a `Meta` and outside of a `ModelSerializer`. `ModelSerializer` is the only case where a `model` is used in DRF.

This should be the reproduction case:

```python
class NonModelSerializer(serializers.Serializer):
    invoice_amount = MoneyField(
        max_digits=constants.DIGIT_SIZE_10,
        decimal_places=constants.DIGIT_SIZE_2,
        required=False,
        allow_null=True,
    )

    class Meta:
        fields = (
            "invoice_amount"
        )
```

**Comment by phillipuniverse** [comment]
The fix should be pretty easy by gating both `self.parent.Meta` and `self.parent.Meta.model`.

**Comment by benjaoming** [comment]
Makes sense, and sorry about the regression. Seems that despite the test coverage, it's actually hard to change this code much.

I don't use DRF, so I hope that someone else will fix this. Would be happy to do a patch release.

**Comment by benjaoming** [comment]
And thanks for reporting so quickly :+1:

**Comment by phillipuniverse** [comment]
@benjaoming loved how easy it was to contribute!! Candidate fix at #758.

**Comment by stianjensen** [comment]
Nice to avoid this crashing with a simple change, but is a Meta class outside of using a model serializer even valid/meaningful code in drf? Is it not only used to define how to auto-generate a serailizer class from a model?

**Comment by phillipuniverse** [comment]
> but is a Meta class outside of using a model serializer even valid/meaningful code in drf

@stianjensen yes, there are multiple examples from the DRF docs like [multi-field validators](https://www.django-rest-framework.org/api-guide/serializers/#validators).

Also consider inheritance, where maybe a parent serializer class declares some fields as read only and a subclass declares them as not (or vice-versa).
